PC:
  NAME: "rosie"
  IP: localhost

NUC:
  NAME: "charmander"
  IP: 172.16.0.1
  PUB_PORT: 5556
  SUB_PORT: 5555
  GRIPPER_PUB_PORT: 5558
  GRIPPER_SUB_PORT: 5557

GRIPPER:
  PUB_RATE: 40  # Hz for status publishing

ROBOT:
  IP: 172.16.0.2



